In [1]:
import numpy as np
import torch

In [2]:
SEED=2000
np.random.seed(seed=SEED)
torch.manual_seed(SEED)

In [4]:
#Creating a random tensor
x = torch.randn(2,3) # gousian distribution | for uniform rand(2,3)
print(f'Type: {x.type()}')
print(f'Size: {x.shape}')
print(f'Values: \n{x}')

Type: torch.FloatTensor
Size: torch.Size([2, 3])
Values: 
tensor([[-0.4922,  0.0569,  0.1592],
        [ 0.7043, -0.7137, -0.1834]])


In [5]:
# Zeros and ones tensor
x = torch.zeros(2,3)
print(x)
x = torch.ones(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [6]:
# list to tensor
x = torch.Tensor([[2,3,4],[4,3,2]])
print(f'shape: {x.shape}')
print(f' x is : \n{x}')

shape: torch.Size([2, 3])
 x is : 
tensor([[2., 3., 4.],
        [4., 3., 2.]])


In [7]:
# Numpy array to tensor
x =torch.Tensor(np.random.rand(2,3))
print(f' shape: {x.shape}')
print(f' values: \n{x}')

 shape: torch.Size([2, 3])
 values: 
tensor([[0.5705, 0.5645, 0.4884],
        [0.3365, 0.3759, 0.5320]])


In [8]:
# Changing tensortype
x = torch.Tensor(3,4)
print(f'Type: {x.type()}')
x = x.long()
print(f'type : {x.type()}')

Type: torch.FloatTensor
type : torch.LongTensor
